document.addEventListener('DOMContentLoaded',()=>{
  const body=document.body;
  document.querySelectorAll('[data-sidebar-toggle]').forEach(btn=>btn.addEventListener('click',()=>body.classList.toggle('sidebar-open')));
  document.querySelectorAll('[data-sidebar-close]').forEach(el=>el.addEventListener('click',()=>body.classList.remove('sidebar-open')));
  const notificationToggle=document.getElementById('notificationToggle');
  const notificationDropdown=document.getElementById('notificationDropdown');
  const clearNotifications=document.getElementById('clearNotifications');
  if(notificationToggle){notificationToggle.addEventListener('click',(e)=>{e.stopPropagation();notificationDropdown.classList.toggle('active')});}
  if(clearNotifications){clearNotifications.addEventListener('click',()=>{const list=document.getElementById('notificationList');list.innerHTML='<div style="padding:2rem;text-align:center;color:#7a8fa6"><i class="bi bi-inbox" style="font-size:2rem;display:block;margin-bottom:.5rem"></i>No notifications</div>';notificationDropdown.classList.remove('active');const badge=document.querySelector('.notification-badge');if(badge)badge.style.display='none'});}
  document.addEventListener('click',(e)=>{if(!e.target.closest('.notification-center')){notificationDropdown.classList.remove('active');}});
  drawRevenueChart(); drawUserChart(); drawCategoryChart();
});
function drawBars(canvasId,labels,values,color){
  const canvas=document.getElementById(canvasId); if(!canvas) return; const ctx=canvas.getContext('2d'); const dpr=window.devicePixelRatio||1; const rect=canvas.getBoundingClientRect(); canvas.width=rect.width*dpr; canvas.height=rect.height*dpr; ctx.scale(dpr,dpr); const w=rect.width,h=rect.height,p=40; ctx.clearRect(0,0,w,h); ctx.strokeStyle='#e0e7f1';ctx.fillStyle='#7a8fa6';ctx.font='11px -apple-system,BlinkMacSystemFont,Segoe UI';ctx.lineWidth=1; for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke();} const max=Math.max(...values)*1.15; const bw=(w-2*p)/values.length*.55; values.forEach((v,i)=>{const x=p+(w-2*p)*(i+.5)/values.length-bw/2;const bh=(h-2*p)*(v/max);const y=h-p-bh; ctx.fillStyle=color; roundRect(ctx,x,y,bw,bh,6); ctx.fill(); ctx.shadowColor='rgba(0,0,0,.1)';ctx.shadowBlur=4;ctx.fillStyle='#7a8fa6';ctx.textAlign='center';ctx.font='11px system-ui';ctx.fillText(labels[i],x+bw/2,h-16);});}
function drawLine(canvasId,labels,values,color){const canvas=document.getElementById(canvasId); if(!canvas)return; const ctx=canvas.getContext('2d'); const dpr=window.devicePixelRatio||1; const rect=canvas.getBoundingClientRect(); canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.scale(dpr,dpr); const w=rect.width,h=rect.height,p=40;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e0e7f1';ctx.fillStyle='#7a8fa6';ctx.font='11px -apple-system,BlinkMacSystemFont,Segoe UI'; for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke();} const max=Math.max(...values)*1.15,min=Math.min(...values)*.9; const points=values.map((v,i)=>[p+(w-2*p)*i/(values.length-1),h-p-(h-2*p)*(v-min)/(max-min)]);ctx.beginPath();points.forEach((pt,i)=>i?ctx.lineTo(pt[0],pt[1]):ctx.moveTo(pt[0],pt[1]));ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.shadowColor='rgba(0,0,0,.1)';ctx.shadowBlur=4;ctx.stroke();points.forEach(pt=>{ctx.beginPath();ctx.arc(pt[0],pt[1],4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();}); labels.forEach((l,i)=>{ctx.fillStyle='#7a8fa6';ctx.textAlign='center';ctx.font='11px system-ui';ctx.fillText(l,points[i][0],h-16);});}
function drawRevenueChart(){drawBars('revenueChart',['Jan','Feb','Mar','Apr','May','Jun'],[42,58,65,78,92,115],'#3b82f6')}
function drawUserChart(){drawLine('userChart',['Jan','Feb','Mar','Apr','May','Jun'],[520,680,850,1120,1580,2150],'#10b981')}
function drawCategoryChart(){drawBars('categoryChart',['Web','Mobile','Cloud','Enterprise','Support'],[68,54,48,72,38],'#f59e0b')}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
window.addEventListener('resize',()=>{clearTimeout(window.__chartResize);window.__chartResize=setTimeout(()=>{drawRevenueChart();drawUserChart();drawCategoryChart();},150)});
